### PR TITLE
Re-instating hide/show of document field when inserting link

### LINKED ISSUE #86: [Bug] Insert Link from HTMLEditor does not reveal document selection field
When using the TinyMCE editor to insert a link into the body of a page, the _Insert Link_ dialog provides a _Download a document_ option. When this is selected, the appropriate document selection field used to be shown, now it doesn't (as at `1.2.0`).

### PR DESCRIPTION
**Pull request by jaedb**
Resolves #86

### CODE REVIEW

**Comment by dhensby** [comment]
Have you tested this locally and it all works as expected?

**Comment by jaedb** [comment]
All appears to be working smoothly on SilverStripe version 3.3.2. Tested in Firefox and Chrome with no problems.

**Comment by dhensby** [comment]
OK, thanks.

**Comment by dhensby** [comment]
In the future, please don't make PRs from your master branch as it can cause issues in the future when you need to update you master or you make other PRs from the same branch.

See docs here: https://docs.silverstripe.org/en/4.0/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request

**Pull request merged**
